### ISSUE TITLE
Key exchange

### ISSUE THREAD

**Issue by richardschneider** [libp2p/js-libp2p-crypto#114]
# Problem

**As a** key holder
**I want** to exchange the key with other systems
**So that** they can use the same key

**Comment by richardschneider** [comment]
# Solution

Most 'other systems' will accept a key in [PKCS #8](https://tools.ietf.org/html/rfc5208) or [PCKS #12](https://tools.ietf.org/html/rfc7292) format.  Both formats allow encrypting with a password, which we should **enforce**.

PKCS #8 is a natural choice, because the concept of a `certificate` is not currently supported.

**Comment by richardschneider** [comment]
# Design

- [ ] Every `private key class` implements `export ([format], password)`.  
- [ ] [keys](https://github.com/libp2p/js-libp2p-crypto/blob/master/src/keys/index.js) implements `import (data, [format], password)`.

Where *format* defaults to `pkcs-8`.

This allows https://github.com/libp2p/js-libp2p-keychain/issues/7 to create and save keys using this library.

**Comment by richardschneider** [comment]
@diasdavid Have you looked at [jsrassign](https://www.npmjs.com/package/jsrsasign).  It has PKCS 7 and 8 support.

**Comment by diasdavid** [comment]
@richardschneider I never tried it out, but looks like it has what you need.
