### ISSUE TITLE
use uRSA to speed up key generation

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p-crypto#127]
See the comment on: https://github.com/nodejs/node/issues/15116#issuecomment-404781297, uRSA is considerably faster than node-forge.

**Comment by mkg20001** [comment]
Ursa optional (https://www.npmjs.com/package/ursa-optional) could be used as a normal dependency. It's a fork that does not make the install fail if compilation fails (although this still means that `require("ursa-optional")` will fail if ursaNative is not compiled so there should be a node-forge fallback)

**Comment by mkg20001** [comment]
PR #128
