### ISSUE TITLE
Return type from generateKeyPair is inconsistent

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-crypto#129]
If you specify `rsa` as the key type, you get an object with an `export` method.  If you specify `ed25519` you don't, which leads to:

```console
$ jsipfs key gen -t rsa my-rsa-key
generated QmSdrjFr32xsvt6yLnD8LS8Uc4riNnRUS4eLT6qogYT2P9 my-rsa-key
$ jsipfs key gen -t ed25519 my-ed25519-key
/path/to/js-libp2p-keychain/src/keychain.js:206
          keypair.export(this._(), (err, pem) => {
                        ^

TypeError: keypair.export is not a function
    at keypair.id (/path/to/js-libp2p-keychain/src/keychain.js:206:25)
    at public.hash (/path/to/js-ipfs/node_modules/libp2p-crypto/src/keys/ed25519-class.js:97:7)
    at Multihashing.Multihashing.digest (/path/to/js-ipfs/node_modules/libp2p-crypto/node_modules/multihashing-async/src/index.js:33:5)
...
```

Go does not have the same problem:

```console
$ ipfs key gen -t rsa my-rsa-key
QmTtWZKxgxkyGG4B7uW7eqkNPyuTKGwFGaqJx34hF8SCVL
$ ipfs key gen -t ed25519 my-ed25519-key
12D3KooWNXoeAFst3J9AUeJiKxcjecZL2v16Kq3UfVqK1ADWeaS5
```

**Comment by achingbrain** [comment]
Digging a bit deeper it looks like `ed25519` support was added to go-ipfs in response to https://github.com/ipfs/notes/issues/241 (though it seems to stall on a discussion about first converting peer IDs to be v1 CIDs) and is awaiting https://github.com/ipfs/go-ipfs/issues/3896 to be merged.  Full support never seems to have made it to js-ipfs.

**Comment by lidel** [comment]
ed25519 keys are the default in js-ipfs these days, this was fixed a while ago
