### ISSUE TITLE
Node.js has now RSA KeyPair Gen 🎉

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p-crypto#130]
- Original Proposal - https://github.com/nodejs/node/issues/15116
- PR https://github.com/nodejs/node/pull/22660

**Comment by diasdavid** [comment]
Great news everyone! https://github.com/nodejs/node/pull/22660#issuecomment-423759973

**Comment by diasdavid** [comment]
It happened!!!!

<img width="688" alt="image" src="https://user-images.githubusercontent.com/1211152/47775703-51efe600-dce8-11e8-864c-ea3ef035abbb.png">

https://github.com/nodejs/node/commit/cd8ee2d033fcc5a2dfe81aed9c508076d62a4cd8

https://nodejs.org/dist/latest-v10.x/docs/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/1211152/47775719-60d69880-dce8-11e8-842a-c32ec8bfe97f.png">

![](https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif)

**Comment by diasdavid** [comment]
Now we just need all to move to the new LTS

<img width="257" alt="image" src="https://user-images.githubusercontent.com/1211152/47775815-b1e68c80-dce8-11e8-98e8-af03786402e9.png">

https://nodejs.org/dist/latest-v10.x/docs/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback

**Comment by daviddias** [comment]
@vasco-santos @alanshaw would this be something you can handle soon™?

**Comment by jacobheun** [comment]
@daviddias what's the priority on this? I think we could look at reasonably tackling this early next year. I'm wary of trying to fit this in with the short time we have left for Q4 OKRs.

**Comment by achingbrain** [comment]
Fixed in https://github.com/libp2p/js-libp2p-crypto/pull/219
