### ISSUE TITLE
Support `ed25519` and `secp256k1` in the import method

### ISSUE THREAD

**Issue by satazor** [libp2p/js-libp2p-crypto#145]
Hello!

I was trying to publish a IPNS record using a `ed25519` key after seeing that support for `ed25519` and `secp256k1` keys was added here. I know that peer-id has to be changed to account for different key types, but I still decided to give it a try.

After trying, I concluded that `js-ipfs` calls [`crypto.keys.import`](https://github.com/ipfs/js-ipfs/blob/d2726fbca9da8ed139b75de0c6c0756bb4240109/src/core/components/name.js#L27) and fails because the import method assumes only RSA keys.

I can make a PR that adds support for `ed25519` and `secp256k1 ` keys by first extracting the private key info stored in the pem and react accordingly.

**Comment by satazor** [comment]
//cc @vasco-santos @dignifiedquire @AlbertoElias

**Comment by AlbertoElias** [comment]
That would be amazing if you could get that in. I didn't know that `import` would be necessary for IPNS, and as it wasn't supported for `ed25519` and `secp256k1` beforehand, I didn't worry about it in my PRs

**Comment by satazor** [comment]
After checking `node-forge`, which we are using to import pkcs8 PEM files, I concluded it doesn't yet support them: https://github.com/digitalbazaar/forge/issues/667

I also discovered that they only support PKCS1 pem files and not PKCS8 pem files, meaning `libp2p-crypto` also only supports PKCS1, see https://github.com/digitalbazaar/forge/blob/5478021a7bdbbbc3b2ea981f28a0487b204cea10/lib/rsa.js#L1335. What they return there is a RSAPrivateKey ASN1 structure and then encode it in DER. This format is actually PKCS1, see https://tools.ietf.org/html/rfc3447#appendix-A.1.2. In contrast, PKCS9 evolved to support other key types by creating a wrapper which specified the key algorithm via the PrivateKeyInfo ASN1 structure, see https://tools.ietf.org/html/rfc5208#section-5.

To do this properly, we would need to support PKCS8 either by implementing in `node-forge` or in a library. I' more inclined in doing this in a library, which I actually already started doing. I will share some more details soon.

**Comment by satazor** [comment]
The library is almost finished, here's a glimpse of it: https://github.com/ipfs-shipyard/js-crypto-key-composer/tree/initial-impl

We should use `decomposePrivateKey` in the `import` method to understand the key type and then call the key type specific import method. Moreover, the `composePrivateKey` may be used to create pkcs1/pkcs8 keys, which we need for `ed25519`.

**Comment by dignifiedquire** [comment]
@satazor I think this is good step forward. Any chance you could drop the dependency on node-forge though? Depending on it as little as possible seems to make the most sense for the long term.

**Comment by satazor** [comment]
Here're the things we are depending on:

```js
import pem from 'node-forge/lib/pem';

import { createBuffer } from 'node-forge/lib/util';
import sha1 from 'node-forge/lib/sha1';
import sha256 from 'node-forge/lib/sha256';
import sha512 from 'node-forge/lib/sha512';
import md5 from 'node-forge/lib/md5';
import pbkdf2 from 'node-forge/lib/pbkdf2';
import aes from 'node-forge/lib/aes';
import des from 'node-forge/lib/des';
import rc2 from 'node-forge/lib/rc2';

import random from 'node-forge/lib/random';
```

As you can see, we are depending on concrete files with functionality that we use 100%. We are not importing stuff like `node-forge/lib/pki` and `node-forge/lib/rsa`, which are monolithic files with functionality that we don't use.

If you really need to completely remove the dependency, we could either find equivalent libraries or copy them over, removing and refactoring whatever necessary. Note that this is something we can do now or down the road, as this package is part of `ipfs-shipyard` and may be moved to `libp2p` as well. Let me know what you think.

**Comment by dignifiedquire** [comment]
Seems like there is at least some duplication there, we already have randomness, and aes defined in a way that doesn't require node-forge and is good in the browser and node in this repo. 

For hashing we have everything outside of node-forge as well: the sha family is available from webcrypto, asmcrypto.js and node.js and md5 is available as a standalone version and available natively in node.js

This way we should only need `des`, `pem` , `pbkdf2` and `rc2` from node-forge.

**Comment by DougAnderson444** [comment]
Hi @AlbertoElias , what ever happened to PR#16 https://github.com/libp2p/js-libp2p-crypto-secp256k1/pull/16 addressing this issue? Did it get merged into libp2p-crypto? Looks like everything stopped last April... but was nearly ready?

**Comment by jacobheun** [comment]
Getting support for PEM exporting/import is a bit painful at the moment due to lack of support in forge. Node.js `crypto` support has improved but needs v12+ support for ed25519 keys (it doesn't support seeding keys). Webcrypto doesn't support ed25519 yet, so we still need a lib for browsers.

To get around these issues in the short term, so we can get support sooner rather than later, the plan is to add support for export/import with the libp2p key format (serialized protobuf). We can still encrypt these with a password if provided to keep consistency there. The plan is to eventually support PEM and a variety of other formats, but that will require a significant effort to ensure everything is done properly (node support/browser support/bundle size constraints). 

We can add support to each of the key types and still have RSA default to PEM to avoid breaking things. Later, we could include a breaking change to have RSA also default to libp2p key encodings.

I'm planning on moving forward with this approach as we want to support exporting/importing libp2p key encoding's anyway. If you have concerns/issues let me know. I'm hoping to land a PR this week.

**Comment by jacobheun** [comment]
I'm going to close this. We now support exporting/importing all 3 keys. PEM is only supported for RSA atm, but I will make sure we have an issue to track adding support to the other keys in the future.

This will be bubbled up to js-ipfs shortly.

**Comment by lidel** [comment]
PEM interop story continues in https://github.com/libp2p/js-libp2p-crypto/issues/244
