### ISSUE TITLE
Make optional arguments last

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-crypto#153]
Methods like the `export` from `src/keys/rsa-class.js` have optional arguments first in their signature.  They should be last to follow conventions.

cc @dirkmc

**Comment by dirkmc** [comment]
I'd suggest we do this immediately after the async changes, and before we do a release, as it's a breaking change

**Comment by jacobheun** [comment]
I agree, since this needs to get pulled into several of the modules, we should make the change before going through that effort. 

The only caveat is that it will make those migrations to async/await a little more confusing in PRs moving the params around.

**Comment by jacobheun** [comment]
async/await is in master, @achingbrain or @dirkmc, do either of you have time to do this? I'm working on a couple of other things but can take this after (likely tomorrow) if neither of you do.

**Comment by dirkmc** [comment]
Sure I can do it
