### ISSUE TITLE
use Node.js native ed25519

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p-crypto#288]
### Done Criteria

Use Node's WebCrypto api implementation of ed25519 key pairs.
https://nodejs.org/docs/latest-v18.x/api/webcrypto.html#ed25519ed448x25519x448-key-pairs

### Why Important
> peer ids/keys using Ed25519 are implemented in JS and therefore they has lower performance compared to e.g. RSA.

 per https://filecoinproject.slack.com/archives/C03K82MU486/p1669827130627229

### Notes
This is still an experimental feature in 18.x
It supports generateKey, exportKey, and importKey but lacks ecrypt, decrypt, wrapKey, and unwrapKey
https://nodejs.org/docs/latest-v18.x/api/webcrypto.html#algorithm-matrix  

> It needs separate node/browser versions in this folder similar to how we have rsa.ts and rsa-browser.ts - https://github.com/libp2p/js-libp2p-crypto/tree/master/src/keys

Per: https://filecoinproject.slack.com/archives/C03K82MU486/p1669827360901159?thread_ts=1669827130.627229&cid=C03K82MU486

**Comment by mpetrunic** [comment]
done https://github.com/libp2p/js-libp2p-crypto/pull/289
