### ISSUE TITLE
Make install less scary - Lookout for prebuilt binaries

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-crypto#31]
ref: https://github.com/PeculiarVentures/node-webcrypto-ossl/issues/69
related: https://github.com/ipfs/js-ipfs-api/issues/416

**Comment by dignifiedquire** [comment]
I think our best bet at this point is to make a PR and setup a pipeline for node-webcrypto-ossl with https://github.com/mapbox/node-pre-gyp

**Comment by diasdavid** [comment]
yes please! :)

**Comment by diasdavid** [comment]
It's less scary now :)
