### ISSUE TITLE
Uncaught error when using browserify

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/js-libp2p-crypto#41]
Below is my code. I use Browserify and run the code in Chrome. The code runs `crypto.generateKeyPair` without issues, but chokes on `peerId.createFromPrivKey` with an Uncaught Exception. See screenshot.

```js
const crypto = require('libp2p-crypto')
const peerId = require('peer-id')

// Example: create an identity
crypto.generateKeyPair('RSA', 2048, (err, key) => {
	if(err) {
		console.error(err);
		return err;
	}

	// So far so good!
	console.log(key);

	// Throws an Uncaught Error!
	peerId.createFromPrivKey(key.bytes, (err, id) => {
		if(err) {
			console.error(err);
			return err;
		}

		console.log(id.toB58String());
	});
});
```

<img width="474" alt="screen shot 2016-11-23 at 12 09 30" src="https://cloud.githubusercontent.com/assets/731743/20561335/06aa31fe-b176-11e6-9760-80af8b354515.png">

**Comment by JustinDrake** [comment]
It doesn't seem to work for me :(

(Still on Chrome with Browserify.)

<img width="849" alt="screen shot 2016-12-04 at 09 46 14" src="https://cloud.githubusercontent.com/assets/731743/20865325/98eb9f10-ba06-11e6-8245-6384e5e6214a.png">

**Comment by dignifiedquire** [comment]
@JustinDrake it doesn't look like you are using the fixed version from the stack trace, are you using `master` from here? The fix was not released yet

**Comment by JustinDrake** [comment]
I think I am using the tip of master. Below is `git log`. What should I do?

<img width="562" alt="screen shot 2016-12-04 at 09 52 47" src="https://cloud.githubusercontent.com/assets/731743/20865364/7b7261de-ba07-11e6-9d29-50ce7772ba9a.png">

**Comment by JustinDrake** [comment]
My bad. For posterity, I installed the latest `master` with the command

`npm install git+https://git@github.com/libp2p/js-libp2p-crypto`
