### ISSUE TITLE
Implement ed25519

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p-crypto#43]
Ref https://github.com/libp2p/go-libp2p-crypto/pull/5

Those will be much faster than RSA key generation :)

**Comment by Kubuxu** [comment]
Simplest way, might not be the fastest, would be to use https://tweetnacl.js.org/#/

ed25519 priv key is random byte array, to create public key scalar multiplication is used.

TweetNaCL reports 170 op/s for normal version and 730 op/s for optimized version for the scalar multiplication operation.
This library implements all relevant functions https://github.com/dchest/tweetnacl-js/blob/master/README.md#signatures and handles entropy sourcing quite well.
