### ISSUE TITLE
webcrypto-liner

### ISSUE THREAD

**Issue by rmhrisk** [libp2p/js-libp2p-crypto#51]
I see you are using node-webcrypto-ossl, I see you are using webcrypto-shim, its a great project but we have a similar one that actually implements algorithms as fallback also, check it out here - https://github.com/PeculiarVentures/webcrypto-liner. With it the project would likley work on IE and Safari as well.

**Comment by dignifiedquire** [comment]
Thank you for pointing this out, I will investigate this =)

**Comment by rmhrisk** [comment]
No problem, the two libraries (node-webcrypto-ossl, webcrypto-liner) share the same code (webcrypto-core) for input validation.

**Comment by achingbrain** [comment]
Closing as stale
