### ISSUE TITLE
ECDSA/secp256k1 support

### ISSUE THREAD

**Issue by parkan** [libp2p/js-libp2p-crypto#57]
We'd like to be able to verify ECDSA (ethereum) signatures. This should be a fairly small amount of work along the lines of #55 

@yusefnapora is on it, opening this here as a head up.

**Comment by parkan** [comment]
@dignifiedquire @diasdavid would adding support for secp256k1 keys [here](https://github.com/libp2p/js-libp2p-crypto/blob/master/src/crypto.proto.js) be in scope? It is (unfortunately) relatively non-standard on paper but de facto the standard in both Bitcoin and Ethereum. I am thinking we would still use sha256 hashing as is done elsewhere in libp2p, so _keys_ would be compatible but signatures not necessarily so (i.e. wouldn't be able to verify signatures from web3.eth.verify because that expects sha3)

The motivation here is improving interop with ethereum for oracles.

**Comment by diasdavid** [comment]
> would adding support for secp256k1 keys here be in scope?

You mean adding another keytype? Absolutely, feel welcome to add, bare in mind though that adding types of keys in the future will be way more sane in the 'near' future as `multikey` develops (each key will be identified by a multicodec, not needing to redefine protobuf files for it). //cc @whyrusleeping 

From several conversations I've been having, it seems more and more people are taking libp2p-crypto as their crypto solution for their needs, which is absolutely great, we definitely had to fight a lot to get all of these crypto primitives the most performant way possible in a way that works for nodejs and the browser, just please always bear in mind this hasn't been audited at all when deploying your systems.

That being said, all sounds good :)

**Comment by parkan** [comment]
PR open at #60
