### ISSUE TITLE
browserify-optional is messing with browserify's ability to process es6

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-crypto#73]
Following https://github.com/libp2p/js-libp2p-crypto/issues/70, now I'm unable to browserify any module that needs libp2p-crypto, as it just rejects anything that is es6. Adding babelify doesn't make it work either.

**Comment by diasdavid** [comment]
I believe that it isn't clear what this library is optimizing for. Currently, we have two dependencies that are causing a lot of friction in the adoption path of js-ipfs:

- libp2p-crypto-secp256k1, which is not bundled by default to avoid increased bundle size (valid concern). This decision has created a lot of pain for browserify users.
- node-webcrypto-ossl, which requires a compilation step, creating some hurdles for electron, windows and linux users -- https://github.com/ipfs/js-ipfs/issues/697 -- https://github.com/ipfs/js-ipfs-api/issues/416. Some of these issues were mitigated, but not 100% (being 100% that no user has a issue.)

We need to step up our process when it comes to merging and releasing things that are so sensitive that can break DX. @dignifiedquire let's talk soon and make a clear roadmap from all of the issues identified and understand what needs to be done for libp2p-crypto, I know you have some good thoughts and I want to help you make these happen.

Meanwhile, because I want to avoid creating problems to our users, I'll go ahead and include `libp2p-crypto-secp256k1` as a dep of the project, avoid breaking support.

**Comment by diasdavid** [comment]
One more note, just spent some time getting out of the circular dependency of `libp2p-crypto` and `libp2p-crypto-secp256k1`, why isn't this DI?

**Comment by dignifiedquire** [comment]
proper fix in 
- https://github.com/libp2p/js-libp2p-crypto/pull/74
- https://github.com/libp2p/js-libp2p-crypto-secp256k1/pull/3

**Comment by diasdavid** [comment]
not an issue anymore
