### ISSUE TITLE
Missing GenerateKeyPairWithReader

### ISSUE THREAD

**Issue by jackkleeman** [libp2p/js-libp2p-crypto#84]
The js implementation lacks the ability to produce keys deterministically, as GenerateKeyPairWithReader in the Go implementation does. Ideally, js-libp2p-crypto would have a function to generate the same key given a seed as the Go implementation would, but at worst any kind of deterministic function would be useful. I am trying to port OpenBazaar to javascript, and currently the best I can do for deterministic key generation from a mnemonic is to have the Go implementation run through GopherJS, which is very slow.

**Comment by dignifiedquire** [comment]
As we use the webcrypto api when available as far as I know we will not be able to provide seeds to do deterministic key generation. The same goes for the nodejs crypto, I'm not seeing any way to do deterministic generation there. 

What do you need deterministic keys for, testing?

**Comment by JustinDrake** [comment]
Deterministic identities are used in OpenBazaar. The user remembers a single mnemonic to deterministically generate both a Bitcoin wallet and a peer id.

**Comment by dignifiedquire** [comment]
Thanks for the info. I will try and figure out what possibilites there are doing this in JavaScript. It will probably be a stand alone tool though, to keep the size of this module as small as possible.

**Comment by jackkleeman** [comment]
That would still be ideal!

**Comment by dignifiedquire** [comment]
So using the latest version of node-forge I was able to do deterministic generation of keys. 

```js
'use strict'

const forge = require('node-forge')
const deepEqual = require('deep-equal')

forge.options.usePureJavaScript = true

const prng = () => {
  const p = forge.random.createInstance()
  p.seedFileSync = function(needed) {
    return forge.util.fillString('a', needed)
  }
  return p
}

const k1 = forge.rsa.generateKeyPair(512, {prng: prng()})
const k2 = forge.rsa.generateKeyPair(512, {prng: prng()})


console.log('same keys', deepEqual(k1.publicKey.n, k2.publicKey.n))
// => true
```

**Comment by jackkleeman** [comment]
Fantastic! What we have found difficult is doing the same for elliptic curve identities, which OB uses. Ideally, we could have the same keys coming from the same seeds in JS and in Go.

**Comment by jackkleeman** [comment]
It seems the elliptic curve library used by go-libp2p generates keys in the same way as tweetnacl, except that go-libp2p first applies scrypt to the seed. I am working on some js code which will produce the same key as go-libp2p given the same seed.

**Comment by dignifiedquire** [comment]
Nice, if that functionality is already in the library, do you want to make a PR for adding this functionality?

**Comment by jackkleeman** [comment]
Yep, no problem
