### ISSUE TITLE
Document style guide, or use eslint or editorconfig file

### ISSUE THREAD

**Issue by jackkleeman** [libp2p/js-libp2p-crypto#86]
It seems that travis runs aegir-lint and fails builds that do not conform. It would be good to have this documented, or even better to have an editorconfig, eslint, etc file in the repo that can be simply used by contributors to check they conform.

**Comment by dignifiedquire** [comment]
All of the js projects from libp2p & ipfs use aegir for linting. The style details for that can be found here: https://github.com/ipfs/community/blob/master/js-project-guidelines.md#linting--code-style though there are some more rules which are not yet explained there: https://github.com/dignifiedquire/aegir/issues/45#issuecomment-275943765

**Comment by diasdavid** [comment]
Can we have Git notify contributors to check that document? Is the only way to add a CONTRIBUTING.md that points to the main one? Probably better than nothing, thoughts?

**Comment by dignifiedquire** [comment]
@diasdavid I think the idea to solve this is https://github.com/ipfs/community/issues/241

**Comment by diasdavid** [comment]
Ok, let's track it there then https://github.com/ipfs/community/issues/241
