### ISSUE TITLE
Enable WebWorkers to make it go faster

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-crypto#9]
node-forge supports WebWorkers
![image](https://cloud.githubusercontent.com/assets/1211152/18415655/05e12ada-77c8-11e6-8a51-e91ba5b5be1d.png)

enable here: https://github.com/libp2p/js-libp2p-crypto/blob/master/src/keys/rsa.js#L131

**Comment by dignifiedquire** [comment]
Sorry, but this is already enabled, the default is `2` workers: https://github.com/digitalbazaar/forge/blob/master/js/rsa.js#L1574

**Comment by VictorBjelkholm** [comment]
Guess it would make sense to set it to `os.cpus().length` by default (for us at least) rather than 2.

**Comment by Kubuxu** [comment]
Why not use `-1` as suggested?

**Comment by VictorBjelkholm** [comment]
> os is not available in the browser, and web workers are only available in the browser

Sorry, `navigator.hardwareConcurrency` would be more appropriate in browser land. Otherwise https://github.com/feross/cpus might help abstract it all away.

**Comment by dignifiedquire** [comment]
> Why not use -1 as suggested?

Yes we could use the internal estimator `-1`.

**Comment by dignifiedquire** [comment]
Oh, I'm so sorry everyone libp2p-crypto currently uses the blocking sync version. So this is an issue. It means I need to change the interface, but will do that asap and switch to the faster async version...

**Comment by dignifiedquire** [comment]
It's not as easy as I would like, as we are depending on this being synchronous in the constructors of js-peer-id and js-peer-info. That means changing this requires as us to refactor the use of all those constructors to methods like `createPeerId(cb)`.

**Comment by diasdavid** [comment]
@dignifiedquire can we get a bench test to run in a couple of laptops to see if node-forge is efficient using WebWorkers? I want to know if we save enough time that justifies all of those changes

**Comment by dignifiedquire** [comment]
@diasdavid we need to make the change in any case to use webcrypto later down the line, i.e. all crypto operations should be done async everywhere. But will need to generate some tests what speed diffs we get

**Comment by dignifiedquire** [comment]
Fixed in #12
